SUSE/suse-best-practices

- xml/MAIN-SBP-publiccloudinfra.xml
for cloud update infrastructure.
> - Add monitoring recommendations for SMT and region server configuration

- xml/MAIN-SBP-Quilting-OSC.xml
> Quilting-OSC: Fix wrong abbreviation

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-Alicloud.adoc
hopefully the last change :-)
Bernd
> typo correction

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-Alicloud.adoc
We have fixed some typos, improved the tuning section and reviewed the list of quoted SAP Notes. In the list of SAP notes we have removed the SLE11 Notes as they are not longer relevant. And we added the HANA 2.0 central note.
> editorial review November 2018

- adoc/SAP_S4HA10_SetupGuide.adoc
- adoc/make.sh
fix duplicate picture, add the correct one
> S/4 HANA HAE Best Practice

- xml/MAIN-SBP-scominstallguide.xml
- xml/MAIN-SBP-scomusermanual.xml
Yah, the titles are even longer now.
(I know I said I'd let you do that, Meike, but it was on one of my cards here, and I do everything my cards tell me to do.)
> SCOM papers: Don't rely on subtitle for the actual guide name

- xml/MAIN-SBP-SLE-OffLine-Upgrade-Local-Boot.xml
> Offline Upgrade Paper: Make title clearer

- xml/SLES-JeOS-12SP4-Quickstart.xml
Mostly Indent cleanup and a few deletion based on the output of https://susedoc.github.io/suse-best-practices/master/SLES-JeOS-12SP4-Quickstart/html/
> Indent cleanup and a few deletion

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc
- adoc/Variables.adoc
- double checked with Fabian,
- back ported changes from docu team
- added new contrain's for majority maker
- added usage of HANA installation parameter file including password file
- modify SAP section twice
- remove variable and word vandalism :-)
> Update Scaleout 2019_08

- adoc/SAP_HA740_SetupGuide_AWS.adoc
Fixed formatting issues with source boxes, bold print, and table.
Fixes titles (capitalization), punctuation and typos.
> Ha740 aws fixes

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc
fix formating issues chapter 8.3.1 and 8.3.7
please publish the new version after check and merge
Thanks Bernd
> fix formating issues chapter 8.3.1 and 8.3.7

- DC-CaaSP3-DataHub2
- adoc/CaaSP_DH2X_Install_Guide.adoc
removed DRAFT flag from DC-CaaSP3-DataHub2.
> removed DRAFT flag from DC-CaaSP3-DataHub2.

- adoc/CaaSP_DH2X_Install_Guide.adoc
replaced internal domain names with generic ones
> replaced internal domain names with generic ones

- DC-SLES4SAP-hana-sr-guide-PerfOpt-12_AWS
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-AWS.adoc
Hi,
we forgot in the last update the sudoer modification for the sidadm to provide the Hook information into the cluster.
Bernd
> Update SAP HANA SR scale-up "PerOpt" for AWS 

- DC-SLES4SAP-hana-sr-guide-PerfOpt-12
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-docinfo.xml
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12.adoc
- adoc/Var_SLES4SAP-hana-sr-guide-PerfOpt-12-param.txt
- adoc/Var_SLES4SAP-hana-sr-guide-PerfOpt-12.txt
The patches of this PR are all for an update of the
SAP HANA SR scale-up "PerOpt" scenario on SLE12 code base.
These updates are also needed for a clone of the document for SLE15 code base.
> Next version of Scale-Up PerfOpt Guide for SLE12 code base

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12.adoc
PR includes
- adding missing picture titles
- fix some TODO/DONE
- fixed to typos in commands (most important)
> PerfOpt12: Backport fixes from SLE15 to SLE12 documentation

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-AWS.adoc
- adding information regarding HANA maintenance, customer feedback
> Update for SLES4SAP-hana-sr-guide-PerfOpt-12-AWS

- xml/MAIN-SBP-HANAonKVM-SLES12SP2.xml
- xml/MAIN-SBP-IaaS-SAP-Cloud.xml
- xml/MAIN-SBP-Migrate-z-KVM.xml
- xml/MAIN-SBP-SUMA-on-IBM-PowerVM.xml
- xml/MAIN-SBP-performance-tuning.xml
- xml/MAIN-SBP-scomusermanual.xml
- xml/MAIN-SBP-strategy-short.xml
- xml/MAIN-SBP-strategy.xml
- xml/MAIN-SBP-sumaforrhel.xml
- xml/SLES-JeOS-12SP4-Quickstart.xml
- xml/entity-decl.ent
- xml/image_studio_pointer.xml
Fixed links with "www.suse.com/documentation" to
"documentation.suse.com" in the xml files using the replinker.py script.
According to daps some links are still broken, but these were broken already and I didnt know how to fix them.
> Link fixes

- adoc/SAP_HA740_SetupGuide_AWS.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-AWS.adoc
updated the move-ip AWS IAM policy and added a statement on having all cluster components in a single AWS accounts
> Docu updates aws

- adoc/SAP_HA740_SetupGuide_AWS.adoc
The chapter Cluster Integration of Fault Manager was missing so far.
> adding missing implementation step, FM -> cluster

- xml/MAIN-SBP-rook-ceph-kubernetes.xml
Some updates to Rook best practices doc including some whitespace stuff my editor saved automatically.
Pinging @asettle
> Blaine updates

- adoc/Veeam95-SES55-Object-guide.adoc
This PR contains the following changes:
* Change list from itemized to ordered
* Uncomment lots of lines to make a first working draft (this is a TODO).
* Correct section level to make it valid
* Turn last two sections into appendix
* Add missing appendix ID
> First start of correcting list bugs

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15-AWS-docinfo.xml
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15-AWS.adoc
This PR creates the SAP HANA Scale Up Performance Optimized scenario using SLES15 for AWS:
- Used the latest official SLES15 SAP HANA Scale-Up document as template
- Updated the existing AWS sections
- Rewording of sentences and spelling fixes
- Technical changes:
- Changed "stonith-timeout" to 600s
- Changed "monitor" internal for EC2 STONITH from 180 to 300
- Changed corosync's token to 30000 (30s) and consensus to (token*1,2) - 36000 (36s)
- Added "pcmk_delay_max" to EC2 STONITH with 15s
> New SLES15 SAP HANA HA Scale Up Guide for AWS

- adoc/Private-Registry-Installation.adoc
Also, fix the level of list ordering for the main installation section.
> Add information about resource management (jsc#CAPS-189)

- adoc/Private-Registry-Installation.adoc
Fix directory name and add securityContext to redis.yaml
> Fixes to redis-operator installation in private registry docs

- adoc/SAP_S4HA10_SetupGuide_SLE15.adoc
> fixing issues 117 and 118

- adoc/Private-Registry-Administration.adoc
- adoc/Private-Registry-Installation.adoc
Document more Day 2 operations for SUSE Private Registry, as well as providing a github token for trivy.
> SPR: document more day 2 operations and trivy github token (CAPS-199, CAPS-201)

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc
> Issue134 133

- adoc/Private-Registry-Airgap.adoc
- adoc/Private-Registry.adoc
As requested, I have imported the air-gapped Private Registry installation guide from:
https://confluence.suse.com/display/ENGCTNRSTORY/Using+k3s+as+air-gapped+environment+for+SUSE+Private+Registry
I converted it to AsciiDoc using Pandoc, have cleaned up and edited it to the best of my ability. This is my first significant piece of work using ADoc.
I have included the single resulting file as-is, and included it directly after the Installation section.
I am sure this needs further work but it's already taken 2 days longer than expected!
> Sbp privatereg airgap

- adoc/Private-Registry-Administration.adoc
Adds the `Backup and Restore` section at the Administration
guide for SUSE Private Registry.
> Add 'Backup and Restore' section for Private Registry

- adoc/Private-Registry-Installation.adoc
As I just recently merged https://github.com/SUSE/suse-best-practices/pull/138 and https://github.com/SUSE/suse-best-practices/pull/139, I thought it was a good time to give a quick copy-edit to the whole chapter. I have removed passive voice wherever possible and tried to simplify the wording slightly. There should not be any changes to the meaning or examples.
> Copy-edit Installation chapter

- xml/MAIN-SBP-GCC-10.xml
I've fixed two validation issues. Both where related to block elements inside other block elements.
> Fix validation issues in MAIN-SBP-GCC-10.xml

- adoc/TRD-sql-server-getting-started.adoc
@bwgartner have incorporated some of you feedback here.
> sql server getting started - remove code indents, data loading

- adoc/SAP-DI-30-CaaSP42-Install-Guide.adoc
This was a big one!
I have tried to improve the formatting a little as well as language and proofreading. 
There are quite a lot of //FIXME comments and so on in this. I hope that it is acceptable as-is.
> Copy edit of SAP DI3 on CaaSP 4.2 install guide SBP (LGHP)

- adoc/SAP-NetWeaver-7.50-SLE-15-Setup-Guide-AliCloud.adoc
fixing variable usage ASE DB installation, 
fixing broken internal link
> review after publishing

- adoc/SAPDI31-RKE-Instguide-docinfo.xml
- adoc/SAPDI31-RKE-Instguide.adoc
some small changes. see comments in commits.
> Usc di rke1

- xml/MAIN-SBP-CSP-UpdateInfra.xml
This PR contains minor updates, mostly formatting, that are recommended before publishing.
> Minor updates to MAIN-SBP-CSP-UpdateInfra

- xml/MAIN-SBP-KMP-Manual-SLE12SP2.xml
Update based on https://bugzilla.suse.com/show_bug.cgi?id=1181033
> KMP Manual: Add codeSigning EKU setting for signing key generation

- adoc/SLES4SAP-HANAonKVM-15SP2.adoc
Hi @chabowski,
I did some final changes to the document, including the ones you proposed in PR #231
Thanks,
Gereon
> fix URLs, headings, formatting

- xml/MAIN-SBP-rook-ceph-kubernetes.xml
removeOSDsIfOutAndSafeToRemove is the correct form which is set in cluster.yaml file. (NOT "removeOSDS..."!)
> Configuration directive corrected

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12-AWS.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
Repair pattern to match both possible hook scripts - fixes issue#239
> Fix Issue 239

- adoc/SAPDI31-RKE2-Instguide.adoc
> fixed typo

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
> fix issue #246

- xml/MAIN-SBP-CSP-UpdateInfra.xml
> SBP-CSP-UpdateInfra fix typo

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12-AWS.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
Package name needs to be spelled with uppercase "S" so correct is: SAPHanaSR-ScaleOut
> Fix issue 259

- misc/build_local_All_SAP_HA_Docs
- misc/build_local_SAP_HA_SimpleMount
- misc/build_local_SAP_HA_hana-scaleOut-PerfOpt-15
- misc/lib_build_local
Add misc directory to share helper scripts to easy build locally using daps2docker.
Also other helper scripts could be placed here.
> Misc directory to share help scrips

- adoc/SLES4SAP-sap-infra-monitoring.adoc
Updated build instructions for pcm. Thanks @twillhal for bringing this up.
> update pcm build instructions (issue SUSE#266)

- adoc/SLES4SAP-hana-sr-guide-CostOpt-12.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
two fixes for cost optimized. One for SLE12, one for SLE15 code base. We have used the variables for the SR SAP system instead for the non-replicated SAP system for the location contraint banning the non-replicated system from the first cluster node.
> Fix issue 278

- adoc/SAP_HA740_SetupGuide_AWS.adoc
- adoc/SLES4SAP-hana-sr-guide-perfopt-15-aws.adoc
Still need to confirm about other changes. So please leave issue 225 and associated PR open for now.
> Updated as per issue 225

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-AWS.adoc
Update document to reflect the current settings in the official AWS documentation.
> Aligning values to AWS Docs

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
Add new text to create authorized_keys.
Remove copying hostkesy to authorized_keys.
> Fix issue 297

- DC-SLES-SAP-hana-scaleOut-PerfOpt-12-AWS
- DC-SLES4SAP-hana-scaleOut-PerfOpt-12
- DC-SLES4SAP-hana-scaleOut-PerfOpt-15
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12-AWS.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
* fix issue #299
* added prompt for command line examples
* crm example format (indentation)
> Fix issue 299

- xml/MAIN-SBP-SLSA.xml
Create a new SBP on how SUSE fulfills SLSA L4.
> Create SLSA4 SBP document

- xml/MAIN-SBP-KubeVirt-SLES15SP3.xml
Signed-off-by: Georg Pfuetzenreuter <georg.pfuetzenreuter@suse.com>
Minor touch-up to resolve #305.
Best,
Georg
> Fix issue #305

- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
- adoc/SAP-S4HA10-setupguide-sle15.adoc
- adoc/SAP_HA740_SetupGuide_SLE12.adoc
- adoc/SAP_S4HA10_SetupGuide_SLE12.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/sap-nw740-sle15-setupguide.adoc
…doc SAP_HA740_SetupGuide_SLE12.adoc SAP_S4HA10_SetupGuide_SLE12.adoc sap-nw740-sle15-setupguide.adoc: not to use sapstartsrv feature Autostart, see bug 1200935
> S/4HANA and NetWeaver setup guides: not to use Autostart

- xml/MAIN-SBP-AMD-EPYC-4-SLES15SP4.xml
Fixed upper and lower case issues, according to tech and AMD spelling
> Editing MAIN-SBP-AMD-EPYC-4-SLES15SP4.xml

- xml/MAIN-SBP-AMD-EPYC-4-SLES15SP4.xml
> Correct typo and remove reference to previous test machine configuration

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15-docinfo.xml
Just updated the document date to catch the new version.
> fixed document date

- adoc/SAP-Multi-SID.adoc
- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
- adoc/SAP-S4HA10-setupguide-sle15.adoc
- adoc/SAPNotes_HANA20_15.adoc
- adoc/SAPNotes_s4_2101.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15-docinfo.xml
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
- adoc/Var_SLES4SAP-hana-sr-guide-PerfOpt-15.txt
Hi,
here are several minor fixes and improvements on
SAP-Multi-SID.adoc
SAPNotes_HANA20_15.adoc
SAPNotes_s4_2101.adoc
SAP-S4HA10-setupguide-sle15.adoc
SAP-S4HA10-setup-simplemount-sle15.adoc
SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
SLES4SAP-hana-sr-guide-costopt-15.adoc
SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
SLES4SAP-hana-sr-guide-PerfOpt-15-docinfo.xml
Var_SLES4SAP-hana-sr-guide-PerfOpt-15.txt
Would be great if they could be merged in somewhen.
Regards,
Lars
> HA for SAP setup guides - fixes and improvements

- adoc/SAP-NetWeaver-7.50-SLE-15-Setup-Guide-AliCloud.adoc
- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
- adoc/SAP-S4HA10-setupguide-sle15.adoc
- adoc/SAP_HA740_SetupGuide_AWS.adoc
- adoc/SAP_HA740_SetupGuide_SLE12.adoc
- adoc/SAP_S4HA10_SetupGuide_SLE12.adoc
- adoc/sap-nw740-sle15-setupguide.adoc
... when we load the sapscriptco.so library
> SAP has asked to use DIR_EXECUTABLE instead of DIR_CT_RUN

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
> Issue339 correct command is SAPHanaSR-manageProviders

- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
> Maintenance procedure with ASCS and ERS instances remain running

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
> fix typo in action_on_lost

- adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
Hi,
here is an fix for issues 355 + 356, "-function ListInstances".
Regards,
Lars
> fix for issue 355 + 356

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
Hi,
here is a fix for issue
https://github.com/SUSE/suse-best-practices/issues/364
Regards,
Lars
> SLES4SAP-hana-sr-guide-PerfOpt-15.adoc: sudoers example, git issue #364

- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
- adoc/SAP-S4HA10-setupguide-sle15.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
- adoc/sap-nw740-sle15-setupguide.adoc
Hi,
here are
- sap-nw740sle15-setupguide: simple mount example in appendix
- SAP-S4HA10-setup-seimplemount: priority fencing example in appendix
- all SUSE HA for SAP setup guides: link to supported scenarios overview
Regards,
Lars
> updates for sap-nw740-sle15-setupguide and SAP-S4HA10-setup-simplemount

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/Variables_HA740.adoc
Hi,
fixed issue 215 et al.
Regards,
Lars
> fixed issue 215 et al

- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
- adoc/SAP-S4HA10-setupguide-sle15.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
Hi Meike,
small fixes for 
SLES4SAP-hana-sr-guide-PerfOpt-15
and
SAP-S4HA10-setup-simplemount-sle15
Regards,
Lars
> fixes for issues #323 and #345

- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
Hi,
SAP-S4HA10-setup-simplemount-sle15.adoc:  fix issue #382
Regards,
Lars
> SAP-S4HA10-setup-simplemount-sle15.adoc:  fix issue #382

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
Hi, 
SLES4SAP-hana-scaleOut-PerfOpt-15.adoc: github issue #260
Regards,
Lars
> SLES4SAP-hana-scaleOut-PerfOpt-15.adoc: github issue #260

- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
SAP-S4HA10-setup-simplemount-sle15.adoc: fstab example git issue #386
> SAP-S4HA10-setup-simplemount-sle15.adoc: fstab example git issue #386

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc
Hi,
I have added HAD provider takeover blocker for HANA scale-out:
SLES4SAP-hana-scaleOut-PerfOpt-15.adoc SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc: susTkOver.py
You kindly might check and merge at your conveniance.
Regards,
Lars
> SLES4SAP-hana-scaleOut-PerfOpt-15.adoc SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc: susTkOver.py

- DC-SAPDI3-RKE2-Installation
- DC-SAPDI3-SUSE-VMWare-VSAN
- adoc/SAPDI3-RKE2-Install-docinfo.xml
- adoc/SAPDI3-RKE2-Install.adoc
- adoc/SAPDI3-SUSE-VMWare-VSAN-Install.adoc
- adoc/SAPDI3-SUSE-VMWare-VSAN-Requirements.adoc
- adoc/SAPDI3-SUSE-VMWare-VSAN-docinfo.xml
- adoc/SAPDI3-SUSE-VMWare-VSAN.adoc
- adoc/SAPDI3-Vsphere-Vsan.adoc
New document on installing SAP DI 3 on top of RKE2 and VMware vSphere / vSAN
> New document on installing SAP DI 3 on top of RKE2 and VMware vSphere / vSAN

- adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
- adoc/SAP-S4HA10-setupguide-sle15.adoc
- adoc/sap-nw740-sle15-setupguide.adoc
hint on RA timeout, issue #392
> hint on RA timeout, issue #392

- adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc
Hi,
SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc: sudoers issues #413
Regards,
Lars
> SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc: sudoers issues #413

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
Hi,
I changed cln_SAPHanaTopology to cln_SAPHanaTop, matching scale-out.
Might go to one of the next updates.
Regards,
Lars
> SLES4SAP-hana-sr-guide-PerfOpt-15 SLES4SAP-hana-sr-guide-costopt-15: minor change

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
Hi,
minor fix in the appendix:
SLES4SAP-hana-sr-guide-PerfOpt-15.adoc: order Optional:
Regards,
Lars
> SLES4SAP-hana-sr-guide-PerfOpt-15.adoc: order Optional:

- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc
Hi Meike,
I have aligned the SAPHanaSR scale-out setup guides´ handling of maintenance during setup with the scale-up perf-opt guide.
Might go into next document update.
Regards,
Lars
> SAPHanaSR-ScaleOut plain and multitarget setup guide: maintenance during setup

- adoc/SAP-NetWeaver-7.50-SLE-15-Setup-Guide-AliCloud.adoc
- adoc/SAP_HA740_SetupGuide_AWS.adoc
- adoc/SAP_HA740_SetupGuide_SLE12.adoc
- adoc/sap-nw740-sle15-setupguide.adoc
- l10n/ko-kr/xml/SAP_HA740_SetupGuide_AWS.xml
According to https://me.sap.com/notes/2177923/E this is named `Start_Program` and not `Start_Programm`.
> Fix `Start_Programm` to be `Start_Program`

- adoc/SAP-convergent-mediation-ha-setup-sle15.adoc
- adoc/SLES4SAP-hana-angi-perfopt-15.adoc
Hi,
fixed a few typos and formatting in
- SLES4SAP-hana-angi-perfopt-15
- SAP-convergent-mediation-ha-setup-sle15
Regards,
Lars
> SLES4SAP-hana-angi-perfopt-15 SAP-convergent-mediation-ha-setup-sle15

- adoc/SAP-convergent-mediation-ha-setup-sle15.adoc
Hi Meike,
I just fixed a header in SAP-convergent-mediation-ha-setup-sle15.adoc.
Do you think this could go into the next update?
Regards,
Lars
> SAP-convergent-mediation-ha-setup-sle15.adoc: fixed sub-section header

- adoc/SAP-EIC-Main.adoc
Hey Meike,
I added the related versions for our solutions to the SAP Edge Integration Cell guide.
Can you please submit the PR? :) 
Thanks!
> Adding versions for LH and Rancher to SAP EIC guide

- adoc/SLES4SAP-hana-angi-perfopt-15.adoc
Hi,
fix for
https://documentation.suse.com/sbp/sap-15/html/SLES4SAP-hana-angi-perfopt-15/index.html#id-saphanafilesystem
---
interval=12
== should be ==>
interval=120
---
Regards,
Lars
> SLES4SAP-hana-angi-perfopt-15.adoc: fix interval=12

- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
Hi,
short update to address issue #446.
Regards,
Lars
> SLES4SAP-hana-sr-guide-PerfOpt-15.adoc: clarify test case, issue #446

- adoc/SAP-EIC-ImagePullSecrets.adoc
- adoc/SAP-EIC-LoginRegistryApplicationCollection.adoc
- adoc/SAP-EIC-Main-docinfo.xml
- adoc/SAP-EIC-Main.adoc
- adoc/SAP-EIC-Metallb.adoc
- adoc/SAP-EIC-PostgreSQL.adoc
- adoc/SAP-EIC-Redis.adoc
- adoc/SAP-EIC-SLEMicro.adoc
- adoc/SAP-Rancher-RKE2-Installation.adoc
- adoc/SAPDI3-Longhorn.adoc
- adoc/SAPDI3-RKE2-Install.adoc
- adoc/SAPDI3-Rancher.adoc
- adoc/SAPDI3-SUSE_Kubernetes_Stack.adoc
- images/src/svg/SAP-EIC-Architecture-RKE2.svg
- images/src/svg/SAP-EIC-Architecture-Rancher.svg
- images/src/svg/SAP-EIC-Architecture.svg
Updating the SAP Edge Integration Cell Guide to v1.1
Major changes:
* Adding HA subscription to Preparations
* Adding explenation for $ and #
* Use rac for installation of cert-manager
* Adding first landscape overview
* Change of metallb and longhorn parititon
* Added Longhorn partition and remove MetalLB kernel parameter.
* Added Version Table
> SAP Edge Integration Cell v1.1

- adoc/SLES4SAP-hana-angi-perfopt-15.adoc
- adoc/SLES4SAP-hana-angi-scaleout-perfopt-15.adoc
- adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
- adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
Hi Meike,
based on feedback from field, I have enhanced
SLES4SAP-hana-angi-perfopt-15.adoc
SLES4SAP-hana-angi-scaleout-perfopt-15.adoc
SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc 
SLES4SAP-hana-sr-guide-PerfOpt-15.adoc
SLES4SAP-hana-sr-guide-costopt-15.adoc:
with more specific requirements, dos and don´ts.
Not urgent.
Regards,
Lars
> SLES4SAP-hana guides: requirements, dos and don´ts

- adoc/SLES4SAP-hana-angi-perfopt-15.adoc
Hi,
fix for issue 458.
Regards,
Lars
> issue 458: SLES4SAP-hana-angi-perfopt-15.adoc: fixed typo in colocation

- xml/MAIN-SBP-performance-tuning.xml
Fill empty table head entries to make the document fully compliant to EAA 25.
> Fix table accessibility issue

- DC-SBP-GCC-14
- images/src/svg/gcc14-specfp-o3-fastmath-perf-geomean.svg
- images/src/svg/gcc14-specfp-o3-fastmath-perf-indiv.svg
- images/src/svg/gcc14-specfp-ofast-pgolto-perf-indiv.svg
- images/src/svg/gcc14-specfp-ofast-pgolto-size.svg
- images/src/svg/gcc14-specfp-ofast-vs7-geomean.svg
- images/src/svg/gcc14-specfp-ofast-vs7-indiv.svg
- images/src/svg/gcc14-specfp-ofast-vsicx-geomean.svg
- images/src/svg/gcc14-specfp-ofast-vsicx-indiv.svg
- images/src/svg/gcc14-specfp-ofast-vsllvm-geomean.svg
- images/src/svg/gcc14-specfp-ofast-vsllvm-indiv.svg
- images/src/svg/gcc14-specint-o2-pgolto-perf-geomean.svg
- images/src/svg/gcc14-specint-o2-pgolto-perf-indiv.svg
- images/src/svg/gcc14-specint-o2-pgolto-size-exchange.svg
- images/src/svg/gcc14-specint-o2-pgolto-size.svg
- images/src/svg/gcc14-specint-ofast-pgolto-perf-geomean.svg
- images/src/svg/gcc14-specint-ofast-pgolto-perf-indiv.svg
- images/src/svg/gcc14-specint-ofast-pgolto-size.svg
- images/src/svg/gcc14-specint-ofast-vs7-geomean.svg
- images/src/svg/gcc14-specint-ofast-vs7-indiv.svg
- images/src/svg/gcc14-specint-ofast-vsicx-geomean.svg
- images/src/svg/gcc14-specint-ofast-vsicx-indiv.svg
- images/src/svg/gcc14-specint-ofast-vsicx-x264-128.svg
- images/src/svg/gcc14-specint-ofast-vsllvm-exchange.svg
- images/src/svg/gcc14-specint-ofast-vsllvm-geomean.svg
- images/src/svg/gcc14-specint-ofast-vsllvm-indiv.svg
- images/src/svg/gcc14-specint-ofast-vsllvm-x264-128.svg
- xml/MAIN-SBP-GCC-14.xml
This is a refresh of a similar article written for GCC 12 and SLE 15 SP4 (this one is for SP6).
> Added: Advanced Optimization and New Capabilities of GCC 14

- DC-SBP-SLES-SQL
- adoc/SLES-SQL-server-linux.adoc
- adoc/SLES-SQL-support.adoc
The new version has an improved the readability
replacing SUMA by Multi-Linux Manager
adding 3rd party support disclaimer
fixing OS registration procedure
removing one picture
cross checking web links
> MS SQL support statement

- adoc/SLES4SAP-hana-angi-perfopt-15.adoc
Hi Meike,
this PR is for SLES4SAP-hana-angi-perfopt-15.adoc: fixed issue #470
Regards,
Lars
> SLES4SAP-hana-angi-perfopt-15.adoc: fixed issue #470

- adoc/SAP-EIC-Main.adoc
- adoc/SAPDI3-Rancher.adoc
- adoc/SLES4SAP-sap-infra-monitoring.adoc
Fix:
-  https://github.com/SUSE/suse-best-practices/issues/497
- https://github.com/SUSE/suse-best-practices/issues/498
> Fix EIC appendix; Add links for backups

- adoc/SAP-EIC-Harvester-main.adoc
- adoc/SAP-EIC-Harvester.adoc
- adoc/SAP-K8s-HA.adoc
- adoc/SAPDI3-Harvester-Installation.adoc
- adoc/SAPDI3-Rancher.adoc
Hey there,
I fixed #489 and also added some smaller enhancements.
> Fix #489; enhance eic-harvester guide

- adoc/SAP-EIC-Main.adoc
- adoc/SAP-EIC-Netapp.adoc
- adoc/SAP-EIC-Variables.adoc
Hey @chabowski ,
this PR enhances the SAP EIC guide by adding instructions how to install NetApp Trident for Edge Integration Cell.
Can you please review and merge it?
> Adding NetApp Trident docu for SAP EIC
