adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc, adoc/make.sh
In this pr I try to fix a problem with the build document. In some of the examples some variables have not
been replaced correctly. One problem was the {SID} in the /etc/fstab example. The second problem is the variable {sidlc} in the example for output of HDB info.
Let's check, if the build is not ok - did not had the chance to build right now.
=> Fixed typset problem with unreplaced ADOC variables

adoc/Private-Registry-Administration.adoc, adoc/Private-Registry-Installation.adoc, adoc/Private-Registry-Requirements.adoc
The jobservice SPR component is now using the database to
store its persistent state artifacts, instead of a Kubernetes
persistent shared volume.
Removes all mentions of jobservice as a component requiring
persistent storage, which simplifies installation and administration
procedures.
=> SPR - default to database backend for jobservice

xml/MAIN-SBP-GCC-10.xml
- C++ features should not have definitive article
- hyphenate store-to-load
- "although" needs an opposing clause in the same sentence, so connected
two sentences.
- fixed capitalization inside a sentence
- clarify that adding extra complexity is a cost, not a goal
- changed position of "only" so that it is clear it describes "-O2" and
not "because"
- remove definite article in "all omitted benchmarks"
- in big parts -> in large part
- connect two sentences that sound unnatural separated
- remove "up" which was probably left behind when "sped up" was
changed to "made faster"
- perf reftest is the *last* test the we have focused on, not the one
we have focused on
- added a missing indefinite article before AMD Ryzen 7 3700X 8-Core
Processor
- traditional build, not traditional built
=> Last proof reading of the GCC 10 paper

xml/MAIN-SBP-AMD-EPYC-3-SLES15SP2.xml, xml/MAIN-SBP-GCC-10.xml
- AMD requested to change Brent's title to Engineering Manager in
papers published this year (and from now on).
- Toolchain in my title also should be one word
=> Fix titles of Brent Hollingsworth and Martin Jambor

xml/MAIN-SBP-AMD-EPYC-3-SLES15SP2.xml
Typos or outdated info in the example code snippets, mostly.
=> AMD EPYC 3 tuning guide: small last minute fixes

adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-AWS.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-15-AWS.adoc
If the user happens to copy the sample config and leave the `# redundant ring comments` after the ring address it causes a corosync parsing error - "[MAIN ] parse error in config: Not all bind address belong to the same IP family". Moved the comments above ring1_addr as empty lines and lines starting with # are ignored by the parser.
=> Update sample corosync configs to prevent corosync parse errors

xml/MAIN-SBP-KubeVirt-SLES15SP3.xml
Small update for the KubeVirt doc: dropping `macvtap` from the list of supported features since at first the focus will be on `bridge` and `masquerade`.
/cc @chabowski , @jfehlig , @hw-claudio
=> Drop macvtap from supported KubeVirt features

adoc/SAP-Multi-SID.adoc, adoc/SAP-NetWeaver-7.50-SLE-15-Setup-Guide-AliCloud.adoc, adoc/SAP_HA740_SetupGuide_AWS.adoc, adoc/SAP_HA740_SetupGuide_SLE12.adoc, adoc/SAP_HA740_SetupGuide_SLE15.adoc, adoc/SAP_S4HA10_SetupGuide_SLE12.adoc, adoc/SAP_S4HA10_SetupGuide_SLE15.adoc, adoc/SAP_S4HA10_Setup_SimpleMount_SLE15.adoc, adoc/SLES4SAP-HANAonKVM-15SP2.adoc, adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc, adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc, adoc/SLES4SAP-hana-sr-guide-CostOpt-12.adoc, adoc/SLES4SAP-hana-sr-guide-CostOpt-15.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-AWS.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-12-Alicloud.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-12.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-15-AWS.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc, adoc/Var_SLES4SAP-hana-scaleOut-PerfOpt-15.txt, adoc/Var_SLES4SAP-hana-sr-guide-CostOpt-12.txt, adoc/Var_SLES4SAP-hana-sr-guide-CostOpt-15.txt, adoc/Var_SLES4SAP-hana-sr-guide-PerfOpt-12.txt, adoc/Var_SLES4SAP-hana-sr-guide-PerfOpt-15.txt
Fix for various sap related best practices which still pointed to the old landing page (all).
Two documents have been converted from dos2unix because of mixed-mode line termination.
=> SAP Best Practices moved to an own site

xml/MAIN-SBP-rook-ceph-kubernetes.xml
7.1  Ceph MONS:
https://documentation.suse.com/sbp/all/single-html/SBP-rook-ceph-kubernetes/index.html#ceph-mons
Mostly replaced tabs with spaces in YAML sample
=> [doc] 7.1  Ceph MONS - Fixed YAML indentation in Ceph MON placement section

xml/MAIN-SBP-KMP-Manual-SLE12SP2.xml
MAIN-SBP-KMP-Manual-SLE12SP2.xml:  Add info and sample spec file for signing modules during packaging.  
(bsc#1193849)
=> - Add info and sample spec file for signing module during packaging.

README.md
Signed-off-by: Georg Pfuetzenreuter <georg.pfuetzenreuter@suse.com>
Small touch-up to refer to the correct chat room.
I wonder however, is there a place for non-staffers to reach out?
Best,
Georg
=> RocketChat -> Slack

.github/workflows/docbook.yml
Related:
* Add redirect: SUSEdoc/suse-best-practices@3a72d35f
* Remove any SBPs in config: SUSEdoc/susedoc.github.io@107df46e
=> Don't publish SBPs on susedoc.github.io anymore

xml/MAIN-SBP-Quilting-OSC.xml
The right command is `osc submitrequest`.
=> Fixes the command to create a submit request in osc

.github/workflows/docbook.yml
For `action/checkout`, `actions/upload-artifact`, `actions/download-artifact`
=> CI: Use @v3 GH Actions to avoid warnings

adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc
The right command is
/usr/sap/hostctrl/exe/saphostctrl -function ListInstances
=> Fix typo in the command to check the SAP hostagent

DC-SBP-AMD-EPYC-2-SLES15SP1, DC-SBP-AMD-EPYC-3-SLES15SP2, DC-SBP-AMD-EPYC-4-SLES15SP4, DC-SBP-GCC-10, DC-SBP-GCC-11
Some papers didn't validate when switching GHA gha-validate from GeekoDoc version 1 to version 2 as default.
=> Switch to DocBook 5 to validate some papers

l10n/ja-jp/DC-SBP-SAP-HANA-PerOpt-HA-Azure, l10n/ja-jp/DC-SBP-Spectre-Meltdown-L1TF, l10n/ja-jp/DC-SBP-susemanager, l10n/ja-jp/DC-SLES-SAP-hana-scaleOut-PerfOpt-12-AWS, l10n/ja-jp/DC-SLES4SAP-hana-sr-guide-PerfOpt-15, l10n/ko-kr/DC-RKE2-SAP-DI31, l10n/ko-kr/DC-SAP_HA740_SetupGuide_AWS, l10n/ko-kr/DC-SAP_S4HA10_SetupGuide-SLE15, l10n/ko-kr/DC-SBP-SAP-HANA-PerOpt-HA-Azure, l10n/ko-kr/DC-SBP-Spectre-Meltdown-L1TF, l10n/ko-kr/DC-SBP-susemanager, l10n/ko-kr/DC-SLES4SAP-hana-sr-guide-PerfOpt-15, l10n/ko-kr/DC-SLES4SAP-hana-sr-guide-PerfOpt-15_AWS
* `DOCBOOK5_RNG_URI` should point to DocBook 5.2
* `STYLEROOT` should point to the new SBP stylesheets
=> Correct DOCBOOK5_RNG_URI & STYLEROOT

adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc, adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-12.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc, adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc, adoc/SLES4SAP-hana-systemv-appendix.adoc, adoc/Variables_HA740.adoc, adoc/sap-nw740-sle15-setupguide.adoc
Hi,
here are this changes:
SLES-for-SAP-hana-sr-guide-PerfOpt-12: updated references
SLES-for-SAP-hana-sr-guide-PerfOpt-15,
SLES-for-SAP-hana-scaleOut-PerfOpt-15,
SLES-for-SAP-hana-sr-guide-costopt-15,
SLES-for-SAP-hana-scaleout-multitarget-perfopt-15: native systemd integration
sap-nw740-sle15-setupguide: simple-mount appendix
Regards,
Lars
=> SLES-for-SAP HA guides update - mainly native systemd integration

adoc/SAPDI3-Install.adoc
Fixing bug [396](https://github.com/SUSE/suse-best-practices/issues/396) by updating the API version of ingress to later version.
=> Fixed SAP DI ingress manifest

adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc, adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc, adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
Hi,
HANA 2.0 SPS05 rev.059 or later is needed with current SAPHanaSR and SAPHanaSR-ScaleOut.
Regards,
Lars
=> SLES4SAP-hana: SPS05 rev.059 Python 3 needed

adoc/SLES4SAP-hana-sr-guide-PerfOpt-12.adoc
Example cluster configuration:
https://documentation.suse.com/sbp/sap-12/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-example-cluster-configuration
We should suggest to use "Optional" and not "2000" when configuring the order as we already did here in the same guide:
https://documentation.suse.com/sbp/sap-12/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#id-constraints
```
order ord_SAPHana_HA1_HDB10 Optional: cln_SAPHanaTopology_HA1_HDB10 \
msl_SAPHana_HA1_HDB10
```
=> SLES4SAP-hana-sr-guide-PerfOpt-12.adoc: order Optional: 

adoc/SAP-S4HA10-setup-simplemount-sle15.adoc
Hi,
SAP-S4HA10-setup-simplemount-sle15.adoc: SAPStartSRv must never have monitor
see also bsc #1221641.
Might go into the next docu update.
Regards,
Lars
=> SAP-S4HA10-setup-simplemount-sle15.adoc: SAPStartSRv must never have monitor

adoc/SLES4SAP-hana-angi-perfopt-15.adoc, adoc/SLES4SAP-hana-angi-scaleout-perfopt-15.adoc, adoc/SLES4SAP-hana-scaleOut-PerfOpt-12.adoc, adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc, adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc, adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
Hi,
here is a fx for
https://github.com/SUSE/suse-best-practices/issues/444
Regards,
Lars
=> to fix issue #444

adoc/SAPDI3-Rancher.adoc
Hotfix: We need to add the RKE2 Version, that we can install RKE2 through Rancher Prime private registry.
The current instructions will lead to a crashing installation process.
=> Hotfix: RKE2 Installation

adoc/SAP-S4HA10-setupguide-sle15.adoc, adoc/sap-nw740-sle15-setupguide.adoc
Hi,
the two setup guides have been obsoleted by thesimple-mount setup.
However, the old concept still is supported for existing clusters.
The respective note might get published with the next update.
Regards,
Lars
=> SAP-S4HA10-setupguide-sle15.adoc sap-nw740-sle15-setupguide.adoc: obsoleted by simple-mount

adoc/SLES4SAP-hana-angi-perfopt-15.adoc, adoc/SLES4SAP-hana-angi-scaleout-perfopt-15.adoc
Hi,
this should fix the {refInst} issue.
Regards,
Lars
=> fix for issue #481

xml/MAIN-SBP-GCC-14.xml
After the GCC 14 SBP got published, our colleague Jan Hubička completed his detailed analysis why 538.imagick_r is slower when built with PGO and the reason is actually different from what we stated in the first version of the paper.  This commit replaces the incorrect one with the correct one.
=> Correct the stated reason why 538.imagick_r is slower with PGO

adoc/SAP-convergent-mediation-ha-setup-sle15.adoc
Hi,
this minor enhancement might go into the next update.
Regards,
Lars
=> SAP-convergent-mediation-ha-setup-sle15.adoc: fixed chapter Checking the operating system

images/src/svg/EPYC4-nas-2vms-sev.svg, images/src/svg/EPYC4-nas-bm-12vm.svg, images/src/svg/EPYC4-nas-bm-1vm.svg, images/src/svg/EPYC4-stream-bm-1vm.svg, images/src/svg/EPYC4-stream-omp-1vm-model.svg, images/src/svg/EPYC4-stream-omp-vms-avg.svg, images/src/svg/EPYC4-stream-omp-vms-sum.svg, images/src/svg/EPYC4-stream-openmp-sev-avg.svg, images/src/svg/EPYC4-stream-single-1vm-model.svg, images/src/svg/EPYC4-stream-single-sev-avg.svg, images/src/svg/EPYC4-stream-single-vms-avg.svg, images/src/svg/EPYC4-stream-single-vms-sum.svg, images/src/svg/EPYC5-nas-1vm-model.svg, images/src/svg/EPYC5-nas-2vms-sev.svg, images/src/svg/EPYC5-nas-bm-16vm.svg, images/src/svg/EPYC5-nas-bm-1vm.svg, images/src/svg/EPYC5-stream-bm-1vm.svg, images/src/svg/EPYC5-stream-omp-1vm-model.svg, images/src/svg/EPYC5-stream-omp-vms-avg.svg, images/src/svg/EPYC5-stream-omp-vms-sum.svg, images/src/svg/EPYC5-stream-single-1vm-model.svg, images/src/svg/EPYC5-stream-single-vms-avg.svg, images/src/svg/EPYC5-stream-single-vms-sum.svg, xml/MAIN-SBP-AMD-EPYC-4-SLES15SP4.xml, xml/MAIN-SBP-AMD-EPYC-5-SLES15SP6.xml
The tuning guide for the AMD EPYC 4 and 5 processors were published without the virtualization section. We agreed with AMD that we would have updated them and add such sections, which is exactly what this PR is doing.
=> Update AMD Tuning Guides for AMD EPYC 4 and 5 Processors

adoc/SAP-EIC-General.adoc, adoc/SAP-EIC-Harvester-main.adoc, adoc/SAP-EIC-ImagePullSecrets.adoc, adoc/SAP-EIC-LoginRegistryApplicationCollection.adoc, adoc/SAP-EIC-Main.adoc, adoc/SAP-EIC-Metallb.adoc, adoc/SAP-EIC-PostgreSQL.adoc, adoc/SAP-EIC-Redis.adoc, adoc/SAP-EIC-SLEMicro.adoc, adoc/SAP-EIC-Variables.adoc, adoc/SAP-K8s-HA.adoc, adoc/SAPDI3-Install.adoc, adoc/SAPDI3-Longhorn.adoc, adoc/SAPDI3-Rancher.adoc, adoc/SAPDI3-SUSE-VMWare-VSAN-Install.adoc, adoc/SAPDI3-Vsphere-Vsan.adoc
After repeatedly receiving feedback about the $ and # annotations in the SAP EIC guides, we decided to change this.
From now on, commands that require to be run as root will start with **sudo** while commands that can be run as any user won't have a prefix any longer.
The advantage of this is, that users can copy & paste commands from the best practices without the need to edit the line before execution.
=> Change EIC annotations

adoc/SLES4SAP-hana-angi-perfopt-15.adoc, adoc/SLES4SAP-hana-angi-scaleout-perfopt-15.adoc, adoc/SLES4SAP-hana-scaleOut-PerfOpt-15.adoc, adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15.adoc, adoc/SLES4SAP-hana-sr-guide-PerfOpt-15.adoc, adoc/SLES4SAP-hana-sr-guide-costopt-15.adoc
Hi Meike,
here is an update on requirements for all SLES4SAP 15 SAPHanaSR setup guides.
The update was initiated by discussions at LinuxLab.
Regards,
Lars
=> SLES4SAP SAPHanaSR setup guides: updates requirememts
